// src/constants/productOptions.ts
export const productTypes = [
    "Rectangular",
    "Square",
    "Round",
    "Square Slab",
    "T Beam",
    "I Beam",
    "L Beam",
    "Precast Column",
    "Precast Wall Panel",
    "Precast Staircase",
    "Precast Lintel",
    "Precast Footing",
    "Double Tee Slab",
    "Hollow Core Slab",
    "Solid Slab",
    "U Drain",
    "Box Culvert",
    "Manhole",
    "Boundary Wall Panel",
    "Retaining Wall",
    "Precast Pile",
    "Precast Bridge Girder",
    "Precast Parapet",
    "Precast Kerb Stone",
    "Precast Gully",
    "Precast Bollard",
    "Precast Pipe",
    "Precast Road Barrier",
  ];
  
  export const productCategories = [
    "Slab",
    "Beam",
    "Column",
    "Wall Panel",
    "Staircase",
    "Foundations",
    "Drainage",
    "Bridges",
    "Utilities",
    "Barriers",
    "Miscellaneous",
  ];


export const productTypesObj = [
  { label: "Rectangular", value: "Rectangular" },
  { label: "Square", value: "Square" },
  { label: "Round", value: "Round" },
  { label: "Square Slab", value: "Square Slab" },
  { label: "T Beam", value: "T Beam" },
  { label: "I Beam", value: "I Beam" },
  { label: "L Beam", value: "L Beam" },
  { label: "Precast Column", value: "Precast Column" },
  { label: "Precast Wall Panel", value: "Precast Wall Panel" },
  { label: "Precast Staircase", value: "Precast Staircase" },
  { label: "Precast Lintel", value: "Precast Lintel" },
  { label: "Precast Footing", value: "Precast Footing" },
  { label: "Double Tee Slab", value: "Double Tee Slab" },
  { label: "Hollow Core Slab", value: "Hollow Core Slab" },
  { label: "Solid Slab", value: "Solid Slab" },
  { label: "U Drain", value: "U Drain" },
  { label: "Box Culvert", value: "Box Culvert" },
  { label: "Manhole", value: "Manhole" },
  { label: "Boundary Wall Panel", value: "Boundary Wall Panel" },
  { label: "Retaining Wall", value: "Retaining Wall" },
  { label: "Precast Pile", value: "Precast Pile" },
  { label: "Precast Bridge Girder", value: "Precast Bridge Girder" },
  { label: "Precast Parapet", value: "Precast Parapet" },
  { label: "Precast Kerb Stone", value: "Precast Kerb Stone" },
  { label: "Precast Gully", value: "Precast Gully" },
  { label: "Precast Bollard", value: "Precast Bollard" },
  { label: "Precast Pipe", value: "Precast Pipe" },
  { label: "Precast Road Barrier", value: "Precast Road Barrier" },
] as const;

export const productCategoriesObj = [
  { label: "Slab", value: "Slab" },
  { label: "Beam", value: "Beam" },
  { label: "Column", value: "Column" },
  { label: "Wall Panel", value: "Wall Panel" },
  { label: "Staircase", value: "Staircase" },
  { label: "Foundations", value: "Foundations" },
  { label: "Drainage", value: "Drainage" },
  { label: "Bridges", value: "Bridges" },
  { label: "Utilities", value: "Utilities" },
  { label: "Barriers", value: "Barriers" },
  { label: "Miscellaneous", value: "Miscellaneous" },
] as const;