// src/constants/productOptions.ts
export const productTypes = [
    "Rectangular",
    "Square",
    "Round",
    "Square Slab",
    "T Beam",
    "I Beam",
    "L Beam",
    "Precast Column",
    "Precast Wall Panel",
    "Precast Staircase",
    "Precast Lintel",
    "Precast Footing",
    "Double Tee Slab",
    "Hollow Core Slab",
    "Solid Slab",
    "U Drain",
    "Box Culvert",
    "Manhole",
    "Boundary Wall Panel",
    "Retaining Wall",
    "Precast Pile",
    "Precast Bridge Girder",
    "Precast Parapet",
    "Precast Kerb Stone",
    "Precast Gully",
    "Precast Bollard",
    "Precast Pipe",
    "Precast Road Barrier",
  ];
  
  export const productCategories = [
    "Slab",
    "Beam",
    "Column",
    "Wall Panel",
    "Staircase",
    "Foundations",
    "Drainage",
    "Bridges",
    "Utilities",
    "Barriers",
    "Miscellaneous",
  ];